// 用語集データ。News/CVE 側からは /glossary#<id> 形式でリンクする。
import { C } from "@/lib/tokens";

export type Cat = "basic" | "attack" | "defense" | "domain" | "tool";

export const CATS: Record<Cat, { name: string; c: string }> = {
  basic: { name: "基礎", c: C.accent },
  attack: { name: "攻撃手法", c: C.pink },
  defense: { name: "防御・組織", c: C.blue },
  domain: { name: "領域", c: C.cyan },
  tool: { name: "ツール・概念", c: C.amber },
};

export type Term = {
  id: string;
  name: string;
  cat: Cat;
  short: string;
  long: string;
  related: string[];
  learn: { label: string; href: string };
};

export const TERMS: Term[] = [
  // ── 基礎 ──────────────────────────────────────────────
  { id: "cve", name: "CVE", cat: "basic", short: "脆弱性に世界共通の番号を振る仕組み。",
    long: "Common Vulnerabilities and Exposures の略。世界中で見つかったソフトウェアやシステムの脆弱性(セキュリティ上の穴)一つひとつに、CVE-西暦-連番 という固有の番号をつけて識別する。番号が共通なので、世界中の誰でも同じ穴の話だと分かる。脆弱性のマイナンバーのようなもの。",
    related: ["0day", "kev", "cvss", "vuln"], learn: { label: "最新CVEを見る", href: "/cve" } },
  { id: "0day", name: "0day", cat: "basic", short: "まだ世に知られていない脆弱性。",
    long: "ゼロデイ。発見されてから対策パッチが公開されるまでの猶予が「0日」しかない、というのが語源。CVE番号もまだ付いていない未公開の脆弱性のこと。発見者しか知らないため極めて価値が高く、攻撃にも防御にも武器になる。CVEは「すでに公になった脆弱性」、0dayは「まだ公になっていない脆弱性」で対をなす。",
    related: ["cve", "exploit", "vuln"], learn: { label: "Recon/OSINTで学ぶ", href: "/roadmap" } },
  { id: "cvss", name: "CVSS", cat: "basic", short: "脆弱性の危険度を0〜10で数値化したスコア。",
    long: "Common Vulnerability Scoring System の略。脆弱性がどれくらい危険かを 0.0〜10.0 の数値で表す業界標準。9.0以上が緊急(Critical)、7.0〜8.9が高(High)、4.0〜6.9が中(Medium)、それ未満が低(Low)。攻撃のしやすさ、認証の有無、影響範囲などを総合して算出される。",
    related: ["cve", "kev"], learn: { label: "CVEのスコアを見る", href: "/cve" } },
  { id: "vuln", name: "脆弱性", cat: "basic", short: "システムにある「セキュリティ上の穴」。",
    long: "Vulnerability。攻撃者が悪用すると、意図しない動作・情報漏洩・乗っ取りなどを引き起こせる欠陥のこと。プログラムのバグ、設定ミス、設計の不備など原因はさまざま。発見されると CVE 番号が振られ、対策(パッチ)が公開され、悪用されたら KEV に載る、という流れが基本。",
    related: ["cve", "exploit", "0day"], learn: { label: "ロードマップ", href: "/roadmap" } },
  { id: "exploit", name: "エクスプロイト", cat: "basic", short: "脆弱性を実際に突くための攻撃コード・手法。",
    long: "Exploit。脆弱性を悪用して、意図した動作(コード実行、情報取得など)を引き起こす具体的な攻撃コードまたは手法。「脆弱性=穴」に対して「エクスプロイト=その穴を通る道具」のような関係。Metasploit のようなフレームワークには、多くの既知エクスプロイトが収録されている。",
    related: ["vuln", "payload", "poc", "rce"], learn: { label: "ロードマップ: Pwn", href: "/roadmap" } },
  { id: "payload", name: "ペイロード", cat: "basic", short: "エクスプロイトの後に実行される本体コード。",
    long: "Payload。エクスプロイトが脆弱性を突いて開けた「実行の入口」を通って、実際に動かしたいコード。シェルを起動する、ファイルをアップロードする、リバース接続を貼る、などの動作を担う部分。エクスプロイト=配達、ペイロード=荷物、と例えられる。",
    related: ["exploit", "rce", "shell", "reverse-shell"], learn: { label: "ロードマップ: Pwn", href: "/roadmap" } },
  { id: "poc", name: "PoC", cat: "basic", short: "脆弱性が実在することを示す検証コード。",
    long: "Proof of Concept。「この脆弱性は本当に悪用できる」と証明するための最小限の検証コードや手順。研究者が公開すると、攻撃者にも防御者にも参考情報になる。GitHubに大量のPoCが公開されており、CVE番号で検索できることが多い。",
    related: ["exploit", "cve", "vuln"], learn: { label: "ロードマップ: Recon", href: "/roadmap" } },
  { id: "attack-vector", name: "攻撃ベクター", cat: "basic", short: "攻撃者が侵入してくる経路や手段。",
    long: "Attack Vector。標的に対してどの経路・手段で攻撃を仕掛けるか、を指す。例: メール添付ファイル、Webアプリの入力欄、開放ポート、USBデバイス、サプライチェーン経由 など。組織は「自社の攻撃ベクター(攻撃面)を把握して塞ぐ」ことを基本戦略とする。",
    related: ["supply-chain", "phishing"], learn: { label: "ロードマップ: Recon", href: "/roadmap" } },

  // ── 攻撃手法 ──────────────────────────────────────────
  { id: "rce", name: "RCE", cat: "attack", short: "遠隔から好きなコマンドを実行できる状態。",
    long: "Remote Code Execution の略。脆弱性を悪用して、攻撃対象のサーバーや端末で攻撃者が任意のコマンドを実行できる状態。実質的に「乗っ取り」を意味し、最も危険なクラスの脆弱性。CVSSスコアが Critical(9.0以上)になるのは、ほぼ RCE 系。",
    related: ["exploit", "shell", "privesc"], learn: { label: "ロードマップ: Pwn", href: "/roadmap" } },
  { id: "xss", name: "XSS", cat: "attack", short: "サイトに悪意あるスクリプトを仕込む攻撃。",
    long: "クロスサイトスクリプティング。ユーザーの入力が適切に処理されていないWebサイトに、攻撃者がスクリプトを埋め込み、それを閲覧した他ユーザーのブラウザで実行させる攻撃。クッキー(セッション情報)の窃取、画面の改ざん、フィッシングなどに使われる。Web脆弱性の中で最も古典的でありながら、今でも非常に多い。",
    related: ["sqli", "csrf", "web"], learn: { label: "ロードマップ: Web L3", href: "/roadmap" } },
  { id: "sqli", name: "SQLi", cat: "attack", short: "DBに不正なクエリを注入する攻撃。",
    long: "SQL Injection の略。Webアプリの入力からデータベースへのクエリ(SQL文)が組み立てられる際、攻撃者が悪意のあるSQL断片を混ぜ込んで、本来取れないデータを取り出したり、認証を突破したりする。古典的だが今も発見される。sqlmap がこの攻撃を自動化するツール。",
    related: ["xss", "web"], learn: { label: "ロードマップ: Web L3", href: "/roadmap" } },
  { id: "csrf", name: "CSRF", cat: "attack", short: "ログイン中のユーザーに勝手に操作させる攻撃。",
    long: "Cross-Site Request Forgery。ユーザーがあるサイトにログインしている状態で、別の罠サイトを踏ませて、ログイン中のセッションを利用した操作(送金・パスワード変更など)を実行させる攻撃。トークンによる防御が必須。",
    related: ["xss", "web"], learn: { label: "ロードマップ: Web", href: "/roadmap" } },
  { id: "mitm", name: "MITM", cat: "attack", short: "通信の途中に割り込んで盗聴・改ざんする攻撃。",
    long: "Man in the Middle、中間者攻撃。AさんとBさんの通信の間に攻撃者が割って入り、盗聴(覗き見)や改ざんを行う。公衆Wi-Fi、ARPスプーフィング、悪意ある証明書などが典型的な手口。HTTPS(暗号化)はこの攻撃への基本的な対抗策。",
    related: ["network"], learn: { label: "ロードマップ: Network", href: "/roadmap" } },
  { id: "supply-chain", name: "サプライチェーン攻撃", cat: "attack", short: "正規ソフトに悪意を混入する攻撃。",
    long: "標的を直接狙わず、標的が使う正規のソフトウェア・ライブラリ・部品の供給経路(サプライチェーン)に悪意あるコードを混ぜ込む攻撃。多くの開発者・組織が使う共通の依存先(npm/PyPI のパッケージ、ベンダーのアップデート機能など)を汚染すれば、一度の攻撃で大量の被害者を生める。SolarWinds事件、3CX事件などが有名。",
    related: ["attack-vector", "cve"], learn: { label: "関連ニュースを見る", href: "/news" } },
  { id: "social-eng", name: "ソーシャルエンジニアリング", cat: "attack", short: "技術ではなく人を騙して情報を引き出す手口。",
    long: "Social Engineering。システムの脆弱性ではなく、人間の心理的な隙(信頼・好意・焦り・権威への服従)を突いて、パスワードや内部情報を引き出す手口の総称。フィッシング、なりすまし電話、ベイティングなどが含まれる。「最も弱い鎖の輪は人間」と言われる所以。",
    related: ["phishing", "attack-vector"], learn: { label: "ロードマップ: OSINT", href: "/roadmap" } },
  { id: "phishing", name: "フィッシング", cat: "attack", short: "偽サイト・偽メールで認証情報を盗む手口。",
    long: "Phishing。正規のサービス(銀行、SNS、社内システム)を装ったメール・SMS・Webサイトに誘導し、ユーザー自身にパスワードや個人情報を入力させて盗む手口。特定個人を狙う「スピアフィッシング」、経営層を狙う「ホエーリング」など派生形も多い。",
    related: ["social-eng", "attack-vector"], learn: { label: "ロードマップ: OSINT", href: "/roadmap" } },
  { id: "bruteforce", name: "ブルートフォース", cat: "attack", short: "総当たりで認証を突破する力技。",
    long: "Brute Force。パスワードや暗号鍵に対して、考えられる組み合わせを片っ端から試す攻撃。Hydraがオンライン認証、HashcatやJohnがオフラインのハッシュ解析でこの手法を高速化する。短い・推測しやすいパスワードは数秒で破られる。多要素認証(MFA)が有効な対策。",
    related: ["hash", "mfa"], learn: { label: "ロードマップ: 暗号", href: "/roadmap" } },
  { id: "dos", name: "DoS / DDoS", cat: "attack", short: "サービスを止めるためにリソースを枯渇させる攻撃。",
    long: "Denial of Service / Distributed DoS。標的のサーバーやネットワークに大量のリクエストを浴びせて、リソース(CPU・帯域・接続数)を枯渇させ、正常なサービス提供を妨害する攻撃。Distributedは「複数のマシン(ボットネット)から一斉に行う」もので威力が大きい。",
    related: ["c2"], learn: { label: "ロードマップ: Network", href: "/roadmap" } },
  { id: "lateral", name: "ラテラルムーブメント", cat: "attack", short: "侵入後に内部を横移動して権限を広げる動き。",
    long: "Lateral Movement。最初の侵入(初期アクセス)で得た足場から、内部ネットワークを横方向に移動して、より重要なシステム・データに到達する動き。盗んだ認証情報の使い回し、SMB/RDPの悪用、ドメイン管理者奪取が典型的。EDR等の検知の山場。",
    related: ["privesc", "shell", "c2"], learn: { label: "ロードマップ: Network", href: "/roadmap" } },

  // ── 防御・組織 ────────────────────────────────────────
  { id: "pentest", name: "ペネトレーションテスト", cat: "defense", short: "侵入を試して穴を見つける検査。",
    long: "Penetration Test、略してペンテスト。攻撃者の視点でシステムに実際に侵入を試み、どこから入れるか・どこまで進めるかを検証する。組織が依頼して実施する正規の作業で、結果として脆弱性が報告書になり、改修される。CTF やバグバウンティはこの技能の隣接領域。",
    related: ["redteam", "ctf"], learn: { label: "ツール集", href: "/tools" } },
  { id: "kev", name: "KEV", cat: "defense", short: "実際に悪用されている脆弱性のカタログ。",
    long: "Known Exploited Vulnerabilities の略。米国 CISA が公開している、現実に攻撃で悪用が確認されたCVEのリスト。米連邦機関は KEV 掲載の脆弱性を期限内に修正する義務がある。理論上危険なだけではなく「今まさに使われている」ため、優先して対処すべきと判断される。",
    related: ["cve", "cvss"], learn: { label: "KEV該当のCVEを見る", href: "/cve" } },
  { id: "redteam", name: "Red / Blue Team", cat: "defense", short: "攻撃役と防御役で対抗演習する役割。",
    long: "レッドチームは組織の許可のもと、実際の攻撃者のように侵入を試みる側。ブルーチームは検知・対応する防御側。両者の演習で、組織の検知能力・対応速度を実戦に近い形で鍛える。中立の評価役を「パープルチーム」と呼ぶこともある。",
    related: ["pentest", "soc", "csirt"], learn: { label: "ロードマップ", href: "/roadmap" } },
  { id: "soc", name: "SOC", cat: "defense", short: "組織のセキュリティを24時間監視するチーム。",
    long: "Security Operations Center。組織のシステムやネットワークから集まるログ・アラートを24時間体制で監視・分析し、攻撃の兆候を検知して初動対応する専門チーム(または部屋)。SIEM などのツールを使い、誤検知の選別と本物のインシデントの拾い上げを両立させる。",
    related: ["csirt", "incident", "redteam"], learn: { label: "ロードマップ: フォレンジック", href: "/roadmap" } },
  { id: "csirt", name: "CSIRT", cat: "defense", short: "インシデント発生時に対応する専門チーム。",
    long: "Computer Security Incident Response Team。セキュリティ事故(インシデント)が起きたときに、影響範囲の特定・封じ込め・復旧・原因分析・再発防止までを担う専門チーム。SOCが「監視」、CSIRTが「対応」と棲み分けることが多い。日本の代表組織はJPCERT/CC。",
    related: ["soc", "incident"], learn: { label: "ロードマップ: フォレンジック", href: "/roadmap" } },
  { id: "incident", name: "インシデント対応", cat: "defense", short: "セキュリティ事故が起きた後の一連の処置。",
    long: "Incident Response。攻撃の検知から、封じ込め・根絶・復旧・教訓化までの一連のプロセス。代表的なフレームに NIST SP 800-61 の「準備 / 検知と分析 / 封じ込め・根絶・復旧 / 事後活動」がある。実戦では時間との勝負で、平時の訓練が物を言う。",
    related: ["csirt", "soc", "forensic"], learn: { label: "ロードマップ: フォレンジック", href: "/roadmap" } },
  { id: "mfa", name: "MFA", cat: "defense", short: "複数の要素で本人確認する認証方式。",
    long: "Multi-Factor Authentication、多要素認証。パスワード(知識)に加え、スマホアプリのコード(所持)、指紋(生体)など、複数の独立した要素で本人確認する。パスワード漏洩だけでは突破できないため、ブルートフォースやフィッシング対策の基本中の基本。",
    related: ["bruteforce", "phishing"], learn: { label: "ロードマップ: Web", href: "/roadmap" } },
  { id: "hardening", name: "ハードニング", cat: "defense", short: "不要機能を削って攻撃面を最小化する作業。",
    long: "Hardening。OS・ミドルウェア・ネットワーク機器などの設定を見直し、不要なサービスや権限を削り、攻撃面を最小限に絞る作業。CIS Benchmarks のようなガイドラインに沿って、デフォルトの緩い設定を本番向けに締め直す。「インストール直後の設定で本番に出さない」が鉄則。",
    related: ["attack-vector"], learn: { label: "ロードマップ: Linux", href: "/roadmap" } },

  // ── 領域 ─────────────────────────────────────────────
  { id: "web", name: "Web", cat: "domain", short: "最も攻撃面が広い領域。",
    long: "HTTP/HTTPS、HTML、JavaScript、データベースなどで構成されるシステム全般。ユーザーが直接触れる入口になることが多く、XSS・SQLi・認証バイパスなど代表的な攻撃手法が集まる。攻撃面が広く、初心者から上級者まで学べるテーマが多い領域。",
    related: ["xss", "sqli", "csrf"], learn: { label: "ロードマップ: Web", href: "/roadmap" } },
  { id: "network", name: "ネットワーク", cat: "domain", short: "通信プロトコル・経路の脆弱性領域。",
    long: "Network。TCP/IP、ルーティング、DNS、ARP、SMB などのプロトコル群と、それらを実装したルータ・ファイアウォール・スイッチ等の機器が対象。MITM、スニッフィング、ARPスプーフィング、ポートスキャンといった古典的かつ強力な技術が集まる領域。",
    related: ["mitm"], learn: { label: "ロードマップ: Network", href: "/roadmap" } },
  { id: "ics", name: "ICS", cat: "domain", short: "電力・水道・工場を動かす制御系。",
    long: "Industrial Control Systems。発電所・上下水道・製造ライン・空調・信号機など、物理世界のインフラを制御するコンピュータ群。インターネットと繋がっていないと思われがちだが、近年は接続されているケースも多く、攻撃されると現実世界に被害(停電・断水・事故)が出る。CISAのICSアドバイザリは、このICS製品の脆弱性情報。",
    related: ["iot", "cve"], learn: { label: "関連ニュースを見る", href: "/news" } },
  { id: "iot", name: "IoT", cat: "domain", short: "ネット接続された日用機器のセキュリティ領域。",
    long: "Internet of Things。家電、監視カメラ、スマートロック、車載機器、医療機器など、ネットに繋がるあらゆる「モノ」。出荷時のパスワードが初期値のまま、ファームウェア更新が無い、暗号化が弱い、などの問題が多く、ボットネット(Mirai等)に組み込まれやすい領域。",
    related: ["ics", "bruteforce"], learn: { label: "ロードマップ: Network", href: "/roadmap" } },
  { id: "osint", name: "OSINT", cat: "domain", short: "公開情報から標的を調べ尽くす技術。",
    long: "Open Source Intelligence。SNS、検索エンジン、公開DB、衛星画像、IoT検索エンジン(Shodan)など、誰でもアクセスできる公開情報から標的の情報を集める技術。攻撃の偵察(Recon)段階で必須であり、調査ジャーナリズムや事件解明にも使われる。",
    related: ["attack-vector", "phishing"], learn: { label: "ロードマップ: Recon/OSINT", href: "/roadmap" } },
  { id: "cloud", name: "クラウド", cat: "domain", short: "AWS/Azure/GCPなどの誤設定が中心の領域。",
    long: "Cloud Security。AWS、Azure、GCP などのクラウドサービス特有のセキュリティ。S3バケットの公開設定ミス、過剰なIAM権限、漏洩したアクセスキー、コンテナイメージの脆弱性などが主な攻撃面。クラウド固有の知識(共有責任モデル等)が必要。",
    related: ["hardening", "attack-vector"], learn: { label: "ロードマップ", href: "/roadmap" } },
  { id: "mobile", name: "モバイル", cat: "domain", short: "iOS/Androidアプリと端末の領域。",
    long: "Mobile Security。iOS / Android のアプリ・OS・端末を対象とする領域。リバースエンジニアリング、ジェイルブレイク/Root化、Intent脆弱性、SSL Pinning回避、安全でないストレージなど、Webや一般PCとは異なる固有のテーマが多い。",
    related: ["reverse-shell"], learn: { label: "ロードマップ", href: "/roadmap" } },
  { id: "forensic", name: "フォレンジック", cat: "domain", short: "インシデント後の証拠保全と解析。",
    long: "Digital Forensics。攻撃や事件のあと、ディスク・メモリ・ログ・通信記録から証拠を保全し、何が起きたか・誰が・どう侵入したかを再構成する技術領域。Volatility(メモリ解析)、Wireshark(通信解析)、Autopsy(ディスク解析)が代表ツール。法的に通用する手続きが求められる。",
    related: ["incident", "csirt"], learn: { label: "ロードマップ: フォレンジック", href: "/roadmap" } },

  // ── ツール・概念 ─────────────────────────────────────
  { id: "shell", name: "シェル", cat: "tool", short: "OSにコマンドを打つための窓口。",
    long: "Shell。ユーザーがOSに命令を打つためのインターフェース。Linux なら bash・zsh、Windows なら PowerShell・cmd。攻撃者が標的のシステムでシェルを取れる(コマンドを打てる状態になる)ことがゴールのひとつ。「シェルを取る」「リバースシェル」などの表現で頻出する。",
    related: ["reverse-shell", "rce", "privesc"], learn: { label: "ロードマップ: Linux", href: "/roadmap" } },
  { id: "reverse-shell", name: "リバースシェル", cat: "tool", short: "標的側からこちらへ接続させるシェル。",
    long: "Reverse Shell。通常のシェル接続は攻撃者→標的だが、ファイアウォールで阻まれることが多い。逆に標的のマシンから攻撃者へ接続させ、その接続上でシェルを動かすのがリバースシェル。多くのファイアウォールが「内→外」の通信を許可している盲点を突く。",
    related: ["shell", "rce", "payload"], learn: { label: "ロードマップ: Pwn", href: "/roadmap" } },
  { id: "privesc", name: "権限昇格", cat: "tool", short: "一般ユーザーから管理者へ昇格する技術。",
    long: "Privilege Escalation。侵入直後は権限の低い一般ユーザーの状態が多い。そこから管理者(root/Administrator)権限を奪取するのが権限昇格。脆弱なサービス、誤った権限設定、SUIDバイナリの悪用などの手口がある。シェルを取った後の次のステップとして、攻撃の流れに必ず出てくる工程。",
    related: ["shell", "lateral", "rce"], learn: { label: "ロードマップ: Linux L4", href: "/roadmap" } },
  { id: "hash", name: "ハッシュ", cat: "tool", short: "一方向に変換した固定長の指紋データ。",
    long: "Hash。任意の長さのデータを、固定長の文字列(指紋)に一方向で変換した結果。元には戻せない、同じ入力からは必ず同じ出力になる、というのが特徴。パスワード保存はハッシュで行うのが基本で、攻撃者は流出したハッシュをHashcatやJohnで「逆算」してくる。",
    related: ["bruteforce"], learn: { label: "ロードマップ: 暗号", href: "/roadmap" } },
  { id: "fuzzing", name: "ファジング", cat: "tool", short: "ランダムな入力を大量に投げて穴を探す手法。",
    long: "Fuzzing。プログラムに対して、変則的・想定外の入力を大量に投げ込み、クラッシュ・例外・異常動作を観察して脆弱性を探す技術。ffuf(Web)、AFL(バイナリ)などが代表ツール。「人間が思いつかない入力で穴を見つける」アプローチで、近年は機械学習も応用される。",
    related: ["exploit", "poc"], learn: { label: "ツール集", href: "/tools" } },
  { id: "c2", name: "C2", cat: "tool", short: "侵入後の端末を遠隔操作する司令塔。",
    long: "Command and Control、コマンド&コントロール。攻撃者が侵入に成功したマシンを遠隔操作するための通信基盤・サーバー。マルウェアは定期的にC2サーバーに「ご注文をどうぞ」と接続しに行く。Cobalt Strikeが代表的なフレームワーク。通信の隠蔽(HTTPS偽装、DNSトンネル)が攻防の焦点。",
    related: ["reverse-shell", "lateral"], learn: { label: "ロードマップ: Network", href: "/roadmap" } },
  { id: "malware", name: "マルウェア", cat: "tool", short: "悪意ある動作を目的とするソフトウェアの総称。",
    long: "Malware。ウイルス、ワーム、トロイの木馬、ランサムウェア、スパイウェア、ルートキットなど、悪意ある動作を目的とするソフトウェア全般を指す総称。攻撃者は標的の端末で動かして、データ窃取・破壊・暗号化・遠隔操作などを行う。検知側はシグネチャ・振る舞い・サンドボックスなど多層で対抗する。",
    related: ["c2", "forensic", "incident"], learn: { label: "ロードマップ: フォレンジック", href: "/roadmap" } },
  { id: "ctf", name: "CTF", cat: "tool", short: "セキュリティ技術を競技で鍛える場。",
    long: "Capture The Flag。出題された脆弱性のあるシステムや暗号文を解いて、隠された「フラグ」を見つけて得点を競う競技。Jeopardy形式(問題に答える)とAttack-Defense形式(チームで攻防)がある。技術を実戦に近い形で鍛えられ、世界中で大会が開催されている。",
    related: ["pentest"], learn: { label: "CTF問題集", href: "/ctf" } },
];
